name: Problem melden
description: Melde eine Problem mit dem Label invalid
title: "[Invalid]: "
labels: ["invalid"]

body:
  - type: textarea
    attributes:
      label: Beschreibe das Problem
      description: Was ist das Problem?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Weitere Beschreibungen
      description: Gibt es noch etwas zu sagen?

  - type: input
    attributes:
      label: App oder Package
      description: An welchen Apps oder Packages müssen Änderungen vorgenommen werden?
      placeholder: z.B. apps/northware-cockpit, package/auth
