name: Bug melden
description: Melde einen schwerwiegenden Bug
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: Beschreibe den Bug
      description: Was ist das Problem?
      placeholder: Beschreibe den Bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Weitere Beschreibungen
      placeholder: Gibt es noch etwas zu sagen?
