name: Security Vulnerability Tracking
description: Tracke eine Security Vulnerbility mit einem Issue
title: "[Security]: "
labels: ["security"]

body:
  - type: input
    attributes:
      label: Link zum Dependbot Alert
      placeholder: https://github.com/ncs-northware/northware/security/dependabot/XX
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Schweregrad
      description: Welcher Schweregrad ist dieser Vulnerability zugeordnet?
      options:
        - High
        - Moderate
        - Low

  - type: input
    attributes:
      label: Betroffenes Package
      placeholder: Wo kommt diese Vulnerability her?

  - type: textarea
    attributes:
      label: Abhängigkeiten (`npm list <vulnerable-dependency>`)
      description: Führe bei Vulnerabilitäten innerhalb der pnpm-lock.yaml bitte "npm list <vulnerable-dependency>" im Terminal aus und füge die Ausgabe hier ein
      placeholder: z.B. Bei einer Vulnerabilität in der dependency "http-proxy-middleware" der Output von "npm list http-proxy-middleware"
      render: bash

  - type: textarea
    attributes:
      label: Beschreibung
      description: Gibt es schon Lösungsansätze?, Gibt es noch etwas zu sagen?
