name: Changesets Auto Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  pull-requests: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 22.19.0
          cache: pnpm
      


      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: "chore(release): New Package Versions"
          title: "chore(release): New Package Versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}